spring:
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        url: jdbc:postgresql://localhost:5432/youtube_cdc?createDatabaseIfNotExists=true
        username: postgres
        password: admin123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# spring.jpa.open-in-view=false

# spring.jpa.properties.hibernate.default_batch_fetch_size = 20